### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by betatim** [wildtreetech/epfl-osip-2017#3]
https://github.com/wildtreetech/advanced-comp-2017/blob/master/install.md

need slight modification for this workshop but should be good to go.

**Comment by mdeff** [comment]
Link will be sent in the common email that will be sent to all participants the 21st.

**Comment by betatim** [comment]
I will try and get a new set of instructions in this repo (with less ML libraries 😃 ).

When do you need it by? If I email it to you at 9am on Thursday?

**Comment by mdeff** [comment]
9am is fine, we'll have our meeting at that time. Not after 9 please ;)
